---
- hosts: all

  become: true

  tasks:
    - name: APT Package Updater
      apt:
        upgrade: yes
        update_cache: yes
    - name: vim
      apt:
        name: vim
        state: latest
    - name: htop
      apt:
        name: htop
        state: latest
    - name: gimp
      apt:
        name: gimp
        state: latest
    
