---
- hosts: all

  become: true

  tasks:
    - name: APT Package Updater
      apt:
        upgrade: yes
        update_cache: yes
    - name: install vim
      apt:
        name: vim
        state: latest
    - name: install htop
      apt:
        name: htop
        state: latest
    - name: install gimp
      apt:
        name: gimp
        state: latest
    
