---
- hosts: all

  become: true

  tasks:
    - name: packages | ensure apt list dir exists
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
    - name: APT Package Updater
      apt:
        upgrade: yes
        update_cache: yes
