---
- hosts: all

  become: true

  tasks:
    - name: APT Package Updater
      apt:
        upgrade: yes
        update_cache: yes
    - name: install vim and ensure its a the latest version
      action: apt name=vim state=present update_cache=yes
    - name: install htop and ensure its a the latest version
      action: apt name=htop state=present update_cache=yes
    - name: install gimp and ensure its a the latest version
      action: apt name=gimp state=present update_cache=yes
    
